name: Publish Action

on:
  workflow_run:
    workflows: [Build Action]
    types: [completed]
  workflow_dispatch:
    inputs:
      release:
        description: 'Publish a new release'
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/v')}}

jobs:
  publish:
    name: Publish
    if: ${{ (github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch') && github.event_name != 'pull_request' }}
    uses: NeoTamia/actions/.github/workflows/jvm-publish.yml@main
    with:
      default-branch: "${{ github.event.repository.default_branch }}"
      release: ${{ startsWith(github.ref, 'refs/tags/v') || github.event.inputs.release }}
    secrets: inherit
